### ISSUE TITLE
no iab module available

### ISSUE THREAD

**Issue by theokirkland** [applied-bioinformatics/iab2#4]
I'm trying to run the Jupyter notebooks from your book on an M1 mac, OS Ventura with Python 3.9.2.  Scikit bio loads, but all cells referring to the iab module fail and I cannot find an iab module.  What am I doing wrong?

**Comment by fomightez** [comment]
Cross posted here](https://stackoverflow.com/q/74815631/8508004). 

Please link when you cross-post so you don't waste multiple people's time answering.   
Importantly, it also helps those having the same issue find the answer later. A 'future you' may be such a person at a later time.

**Comment by ebolyen** [comment]
Thank you @fomightez's your comments on the SO post are correct, there is no iab module in this latest edition of the book. I expect @theokirkland was using the original repository and posted this to the wrong issue tracker.

The source from the first edition is available [here](https://github.com/applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics) and the [runnable version is here](https://github.com/applied-bioinformatics/built-iab).

The last link includes an environment file which can be installed with conda.

**Comment by fomightez** [comment]
Oh got it. I posted over at SO that think just running the following in the notebook may fix @theokirkland 's issue then:

```shell
%pip install https://github.com/caporaso-lab/An-Introduction-To-Applied-Bioinformatics/archive/master.zi
```

Let me know though if you want advice on how to make the rocket button work again from the Edition 2 JupyterBook. (Basically, you should make a directory named `binder` and put a much simpler `environment.yml` in there with the mininum stuff needed, ie., the 'extra' packages as vanilla session doesn't have **& nothing overlapping with things that MyBInder handles already**. I'd start with them unpinned and then see if you can pin them.)

**Comment by theokirkland** [comment]
Thanks

Theo
